### PR TITLE
Add branching guide

### PR DESCRIPTION
**Pull request by calebeby**
Feedback please!

You can preview this at https://deploy-preview-2--pigmice.netlify.com/programming/branching

@BrendanBurkhart 
@octoflo
We should also get review from the other programmers, but I don't know their usernames

### CODE REVIEW

**Comment by brendanburkhart** [comment]
It looks good. The only thing I can think of is that it might be easier to teach new members how to use the graphical tools on GitHub+VSCode (or whatever else we choose to use), and introduce them to cli git as the season progresses.

**Comment by calebeby** [comment]
Good point. I don't know how to use the vs code or atom git tools, so do you want to add that?

**Comment by brendanburkhart** [comment]
Sure. Does it make more sense to have cli and gui git in different sections, or both at each step?

**Comment by calebeby** [comment]
Probably both at each step.

**Comment by calebeby** [comment]
OK, since people don't seem to have any more feedback on this, I'm going to merge this.

Brendan, I think it makes more sense to add the gui tools screenshots/instructions in a separate PR when you get around to it.

**Pull request merged**
